sudo: required
services: 
    - docker

before_install:
    - docker build -t adarsha12/docker-react-app -f Dockerfile.dev .
# run some test and report on whether the test succeded or failed// and exit the test
script:
    - docker run -e CI=true adarsha12/docker-react-app npm run test

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: "ap-southeast-1" 
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-629685160058"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY







