sudo: required
services: 
    - docker

before_install:
    - docker build -t adarsha12/docker-react-app -f Dockerfile.dev .
# run some test and report on whether the test succeded or failed// and exit the test
script:
    - docker run -e CI=true adarsha12/docker-react-app npm run test




